import { Capacitor } from '@capacitor/core';

/**
 * True when the app is running as the native mobile (Capacitor) build.
 *
 * Resolves to true either at build time (VITE_APP_TARGET=mobile) or at runtime
 * when running inside a native Capacitor shell. Web (Lovable) builds are
 * unaffected and continue to see IS_MOBILE === false.
 *
 * This file is owned by the mobile port — it is NOT generated by Lovable.
 */
export const IS_MOBILE =
  import.meta.env.VITE_APP_TARGET === 'mobile' || Capacitor.isNativePlatform();
