/**
 * Job-site proximity check for the native app.
 *
 * Employees may log work / add vehicles when they are within a broad radius of the
 * facility — broad enough to allow catching up nearby (e.g. forgot to add a vehicle),
 * tight enough that a glitch can't let them affect a far-away facility.
 *
 * This is READY but DORMANT: it only activates once the `locations` table stores
 * coordinates. Today `locations` has name + address only (no lat/lng), so
 * `facilityCoords` is null and the check is skipped (work still logs, location is
 * still captured). To turn the gate on:
 *   1. Add `latitude` + `longitude` columns to the `locations` table (via Lovable).
 *   2. Populate them for your facilities (geocode the address, or enter manually).
 *   3. Pass the facility's { latitude, longitude } into checkJobSiteProximity().
 *
 * This file is owned by the mobile port — it is NOT generated by Lovable.
 */

/** Radius allowed between the employee and the facility. Tune freely (25–50 mi range). */
export const JOB_SITE_RADIUS_MILES = 40;

export interface LatLng {
  latitude: number;
  longitude: number;
}

/** Great-circle distance between two points, in miles (Haversine). */
export function distanceMiles(a: LatLng, b: LatLng): number {
  const R = 3958.8; // Earth radius in miles
  const toRad = (d: number) => (d * Math.PI) / 180;
  const dLat = toRad(b.latitude - a.latitude);
  const dLng = toRad(b.longitude - a.longitude);
  const lat1 = toRad(a.latitude);
  const lat2 = toRad(b.latitude);
  const h =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(lat1) * Math.cos(lat2) * Math.sin(dLng / 2) ** 2;
  return 2 * R * Math.asin(Math.min(1, Math.sqrt(h)));
}

export interface ProximityResult {
  /** true when we can't evaluate (no facility coords) — treated as allowed, no gate. */
  skipped: boolean;
  withinRange: boolean;
  distanceMiles: number | null;
}

/**
 * Evaluate whether the employee is close enough to the facility.
 * If either coordinate is missing (facilities have no coords yet), the check is
 * skipped and treated as allowed so nothing is blocked prematurely.
 */
export function checkJobSiteProximity(
  employee: LatLng | null | undefined,
  facility: LatLng | null | undefined,
  radiusMiles: number = JOB_SITE_RADIUS_MILES,
): ProximityResult {
  if (
    !employee ||
    !facility ||
    facility.latitude == null ||
    facility.longitude == null
  ) {
    return { skipped: true, withinRange: true, distanceMiles: null };
  }
  const d = distanceMiles(employee, facility);
  return { skipped: false, withinRange: d <= radiusMiles, distanceMiles: d };
}
