import { useCallback, useState } from 'react';
import { Geolocation, type Position } from '@capacitor/geolocation';

/**
 * Native geolocation for field employees (Capacitor).
 *
 * Provides on-demand access to the device's current position — used to verify
 * an employee is at the correct job site when logging work. This is the app's
 * genuine native capability (satisfies Apple App Store guideline 4.2, which
 * rejects thin web wrappers).
 *
 * This file is owned by the mobile port — it is NOT generated by Lovable.
 */
export interface Coordinates {
  latitude: number;
  longitude: number;
  accuracy: number;
}

export function useGeolocation() {
  const [coords, setCoords] = useState<Coordinates | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const getCurrentPosition = useCallback(async (): Promise<Coordinates | null> => {
    setLoading(true);
    setError(null);
    try {
      // Ask for permission first; on native this shows the OS prompt.
      const perm = await Geolocation.checkPermissions();
      if (perm.location !== 'granted') {
        const req = await Geolocation.requestPermissions();
        if (req.location !== 'granted') {
          setError('Location permission denied');
          return null;
        }
      }

      const position: Position = await Geolocation.getCurrentPosition({
        enableHighAccuracy: true,
        timeout: 10000,
      });

      const next: Coordinates = {
        latitude: position.coords.latitude,
        longitude: position.coords.longitude,
        accuracy: position.coords.accuracy,
      };
      setCoords(next);
      return next;
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Failed to get location');
      return null;
    } finally {
      setLoading(false);
    }
  }, []);

  return { coords, loading, error, getCurrentPosition };
}
