import { Component, ReactNode } from 'react';

interface Props {
  children: ReactNode;
}
interface State {
  error: Error | null;
}

/**
 * Catches render/runtime errors anywhere below it and shows the error instead of
 * a blank white screen. Critical on native (Capacitor) builds, where an uncaught
 * error just leaves a white WebView with no console visible to the user.
 *
 * This file is owned by the mobile port — it is NOT generated by Lovable.
 */
export class AppErrorBoundary extends Component<Props, State> {
  state: State = { error: null };

  static getDerivedStateFromError(error: Error): State {
    return { error };
  }

  componentDidCatch(error: Error, info: unknown) {
    // Surface in the native debug console (Xcode / Logcat) too.
    console.error('[AppErrorBoundary] Uncaught error:', error, info);
  }

  render() {
    const { error } = this.state;
    if (error) {
      return (
        <div
          style={{
            padding: '24px',
            maxWidth: '640px',
            margin: '0 auto',
            fontFamily: 'system-ui, sans-serif',
            color: '#111',
          }}
        >
          <h2 style={{ fontSize: '18px', fontWeight: 700, marginBottom: '8px' }}>
            Something went wrong
          </h2>
          <p style={{ fontSize: '14px', color: '#555', marginBottom: '16px' }}>
            The screen hit an error. Details below:
          </p>
          <pre
            style={{
              whiteSpace: 'pre-wrap',
              wordBreak: 'break-word',
              background: '#f5f5f5',
              border: '1px solid #ddd',
              borderRadius: '8px',
              padding: '12px',
              fontSize: '12px',
              color: '#b00020',
            }}
          >
            {String(error?.message || error)}
            {'\n\n'}
            {error?.stack}
          </pre>
          <button
            onClick={() => {
              this.setState({ error: null });
              window.location.assign('/');
            }}
            style={{
              marginTop: '16px',
              padding: '10px 16px',
              borderRadius: '8px',
              border: 'none',
              background: '#1949E9',
              color: '#fff',
              fontSize: '14px',
              fontWeight: 600,
            }}
          >
            Back to Home
          </button>
        </div>
      );
    }
    return this.props.children;
  }
}
