import { Routes, Route, Navigate } from 'react-router-dom';
import { useAuth } from '@/contexts/AuthContext';
import { ProtectedRoute } from '@/components/ProtectedRoute';
import { PortalProtectedRoute } from '@/components/PortalProtectedRoute';
import Login from './pages/Login';
import { ChangePassword } from './pages/ChangePassword';
import EmployeeDashboard from './pages/EmployeeDashboard';
import Messages from './pages/Messages';
import Unauthorized from './pages/Unauthorized';
// Client portal
import PortalLogin from './pages/portal/PortalLogin';
import PortalSignup from './pages/portal/PortalSignup';
import PortalAuthCallback from './pages/portal/PortalAuthCallback';
import PortalOnboarding from './pages/portal/PortalOnboarding';
import PortalPending from './pages/portal/PortalPending';
import PortalDashboard from './pages/portal/PortalDashboard';
import PortalRequestAccess from './pages/portal/PortalRequestAccess';
import PortalMessages from './pages/portal/PortalMessages';
import PortalLocationHistory from './pages/portal/PortalLocationHistory';
import PortalRequestWash from './pages/portal/PortalRequestWash';

/**
 * Route tree for the native mobile (Capacitor) build.
 *
 * Includes BOTH field-employee screens AND the full client portal. Office /
 * finance / admin / payroll / super-admin routes are intentionally NOT
 * registered here (those stay web-only). Reuses the exact same page components
 * and route guards as the web app — no forked screens.
 *
 * This file is owned by the mobile port — it is NOT generated by Lovable.
 */

/** Mobile root: route a signed-in user to the right home, else to a login. */
const MobileRootRedirect = () => {
  const { user, isPortalUser, loading } = useAuth();

  if (loading) {
    return (
      <div className="flex min-h-screen items-center justify-center">
        <div className="text-center">
          <div className="h-8 w-8 animate-spin rounded-full border-4 border-primary border-t-transparent mx-auto mb-4" />
          <p className="text-muted-foreground">Loading...</p>
        </div>
      </div>
    );
  }

  if (user && isPortalUser) {
    return <Navigate to="/portal/dashboard" replace />;
  }
  if (user) {
    return <Navigate to="/employee/dashboard" replace />;
  }
  return <Navigate to="/login" replace />;
};

export const MobileRoutes = () => (
  <Routes>
    {/* Employee auth + screens */}
    <Route path="/login" element={<Login />} />
    <Route path="/change-password" element={<ChangePassword />} />
    <Route path="/unauthorized" element={<Unauthorized />} />
    <Route path="/" element={<MobileRootRedirect />} />
    <Route
      path="/employee/dashboard"
      element={
        <ProtectedRoute allowedRoles={['employee', 'manager', 'finance', 'admin']}>
          <EmployeeDashboard />
        </ProtectedRoute>
      }
    />
    <Route
      path="/messages"
      element={
        <ProtectedRoute allowedRoles={['employee', 'manager', 'finance', 'admin']}>
          <Messages />
        </ProtectedRoute>
      }
    />

    {/* Client portal — public auth */}
    <Route path="/portal/login" element={<PortalLogin />} />
    <Route path="/portal/signup" element={<PortalSignup />} />
    <Route path="/portal/auth/callback" element={<PortalAuthCallback />} />
    <Route path="/portal" element={<Navigate to="/portal/login" replace />} />

    {/* Client portal — onboarding / pending (any account status) */}
    <Route
      path="/portal/onboarding"
      element={<PortalProtectedRoute allowAnyStatus><PortalOnboarding /></PortalProtectedRoute>}
    />
    <Route
      path="/portal/pending"
      element={<PortalProtectedRoute allowAnyStatus><PortalPending /></PortalProtectedRoute>}
    />

    {/* Client portal — authed */}
    <Route
      path="/portal/dashboard"
      element={<PortalProtectedRoute><PortalDashboard /></PortalProtectedRoute>}
    />
    <Route
      path="/portal/request-access"
      element={<PortalProtectedRoute><PortalRequestAccess /></PortalProtectedRoute>}
    />
    <Route
      path="/portal/messages"
      element={<PortalProtectedRoute><PortalMessages /></PortalProtectedRoute>}
    />
    <Route
      path="/portal/locations/:id"
      element={<PortalProtectedRoute><PortalLocationHistory /></PortalProtectedRoute>}
    />
    <Route
      path="/portal/locations/:id/request-wash"
      element={<PortalProtectedRoute><PortalRequestWash /></PortalProtectedRoute>}
    />

    {/* Anything else bounces to the root redirect. */}
    <Route path="*" element={<Navigate to="/" replace />} />
  </Routes>
);
