import { Capacitor } from '@capacitor/core';
import { Preferences } from '@capacitor/preferences';

/**
 * Auth-token storage adapter for supabase-js.
 *
 * On the web this is plain localStorage (unchanged behavior). Inside a native
 * Capacitor WebView, localStorage can be evicted by the OS, which silently logs
 * employees out. There we back the session in @capacitor/preferences, which is
 * durable native storage. supabase-js supports async storage adapters, so the
 * async methods below are fine.
 *
 * This file is owned by the mobile port — it is NOT generated by Lovable.
 */
export const authStorage = Capacitor.isNativePlatform()
  ? {
      getItem: async (key: string): Promise<string | null> => {
        const { value } = await Preferences.get({ key });
        return value ?? null;
      },
      setItem: async (key: string, value: string): Promise<void> => {
        await Preferences.set({ key, value });
      },
      removeItem: async (key: string): Promise<void> => {
        await Preferences.remove({ key });
      },
    }
  : localStorage;
